import "../fonts/Orbitron-VariableFont_wght.ttf";
import "../fonts/Orbitron-Bold.ttf";
import "../fonts/Orbitron-ExtraBold.ttf";

import { Palette } from "../palette.slint";
import { PlayBar } from "../playbar.slint";
import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export component FilePage {
    
    HorizontalBox {
        padding: 0px;
        spacing: 0px;
        VerticalBox {
            padding: 0px;
            spacing: 0px;

            main_area := Rectangle {
                preferred-height: 480px;
                // width: root.width;
                // height: (root.height - menubar.height - playbar.height);
                // x: 0;
                background: #273537;
            }
        }
    }
}