import "../fonts/Orbitron-VariableFont_wght.ttf";
import "../fonts/Orbitron-Bold.ttf";
import "../fonts/Orbitron-ExtraBold.ttf";

import { Palette } from "../palette.slint";
import { PlayBar } from "../playbar.slint";
import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export component MainPage inherits Rectangle {
    // preferred-width: 800px;

    in property <bool> media_playing;
    in property <bool> file_selected;
    in property <string> media_title;
    in property <string> media_artist;
    in-out property <int> current_time;
    in property <int> total_duration;
    in property <int> resume_update_flag;
    in property <image> background_image;
    in property <length> available_height: 300px;
    in property <[float]> analyzer_bins : [
        0.0,
        0.0,
    ];

    // HorizontalBox {
    //     padding: 0px;
    //     spacing: 0px;
    //     VerticalBox {
    //         padding: 0px;
    //         spacing: 0px;

            main_area := Rectangle {
                preferred-height: 480px;
                // width: root.width;
                height: available_height;
                // x: 0;
                clip: true;
                Image {
                    source: root.background_image;
                    width: self.source.width * 0.5px;
                    height: self.source.height * 0.5px;

                }
                HorizontalLayout {
                    padding: 3px;
                    spacing: 3px;
                    for bin[i] in root.analyzer_bins : Rectangle {
                        width: 20px;
                        Rectangle {
                            height: bin * 1px;
                            background: teal;
                            y: parent.height - self.height;
                        }
                    }
                }
                // background: #562769;
            }
            
    //     }
    // }
}