import { FluentPalette } from "../slint-built-in/styling.slint";
import { SliderBase } from "../slint-built-in/common/slider-base.slint";
import { Palette } from "../palette.slint";

export component SlimSlider { 
    in property <Orientation> orientation <=> base.orientation;
    in property <float> maximum <=> base.maximum;
    in property <float> minimum <=> base.minimum;
    in property <float> step <=> base.step;
    in property <bool> enabled <=> base.enabled;
    out property <bool> has-focus: base.has-focus;
    in-out property <float> value <=> base.value;
    in property <length> thumb-size: 14px;

    in property <color> fill: FluentPalette.accent-background;

    callback changed <=> base.changed;
    callback released <=> base.released;

    min-width: base.vertical ? 20px : 0px;
    min-height: base.vertical ? 0px : 20px;
    vertical-stretch: base.vertical ? 1 : 0;
    horizontal-stretch: base.vertical ? 0 : 1;
    accessible-role: slider;
    accessible-enabled: root.enabled;
    accessible-value: root.value;
    accessible-value-minimum: root.minimum;
    accessible-value-maximum: root.maximum;
    accessible-value-step: min(root.step, (root.maximum - root.minimum) / 100);
    accessible-action-set-value(v) => {
        if v.is-float() {
            base.set-value(v.to-float());
        }
    }
    accessible-action-increment => { base.increment(); }
    accessible-action-decrement => { base.decrement(); }
    forward-focus: base;

    states [
        disabled when !root.enabled : {
            track.background: FluentPalette.border;
        }
        pressed when base.handle-pressed : {
            thumb.width: 10px;
            thumb.background: Palette.accent-background;
            thumb.border-color: FluentPalette.border;
        }
        hover when base.has-hover : {
            thumb.width: 14px;
            thumb.background: Palette.accent-background;
        }
    ]

    rail := Rectangle {
        x: base.vertical ? (parent.width - self.width) / 2 : 0;
        y: base.vertical ? 0 : (parent.height - self.height) / 2;
        width: base.vertical ? 4px : parent.width;
        height: base.vertical ? parent.height : 4px;
        background: FluentPalette.border;
        border-radius: 2px;
    }

    track := Rectangle {
        x: base.vertical ? (parent.width - self.width) / 2 : 0;
        y: base.vertical ? thumb.y + thumb.height / 2 : (parent.height - self.height) / 2;
        width: base.vertical ? rail.width : thumb.x + (thumb.width / 2);
        height: base.vertical ? parent.height - thumb.y - thumb.height : rail.height;
        background: Palette.secondary-accent-background;
        border-radius: rail.border-radius;
    }

    thumb := Rectangle {
        x: base.vertical ? (parent.width - self.width) / 2 : clamp((parent.width - self.width) * (root.value - root.minimum) / (root.maximum - root.minimum), 0, parent.width - self.width);
        y: base.vertical ? clamp((parent.height - self.height) * (root.maximum - root.value) / (root.maximum - root.minimum), 0, parent.height - self.height) : (parent.height - self.height) / 2;
        width: 0px;
        height: self.width;
        border-radius: self.width / 2;
        background: Palette.secondary-accent-background;

        // animate background, width { duration: 50ms; }
    }

    base := SliderBase {
        width: 100%;
        height: 100%;
        handle-x: thumb.x;
        handle-y: thumb.y;
        handle-width: thumb.width;
        handle-height: thumb.height;
    }
}