import { HorizontalBox, VerticalBox, Button } from "std-widgets.slint";
import "fonts/Orbitron-VariableFont_wght.ttf";
import "fonts/Orbitron-Bold.ttf";
import "fonts/Orbitron-ExtraBold.ttf";

import { Palette } from "palette.slint";
import { PlayBar } from "playbar.slint";
import { CustomMenuBar } from "menubar.slint";
import { MainPage } from "pages/main-page.slint";
import { FilePage, MediaData } from "pages/file-page.slint";

export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 128px;
    min-height: 128px;
    max-width: 19200px;
    max-height: 10800px;
    // default-font-family: "Orbitron";
    background: #000000;
    icon: @image-url("icons/teku blue white icon stretch 256.png");
    title: "teku-izer";
    default-font-family: "Orbitron";

    callback check_if_pair_solved();
    // TODO see if i can just pass a MediaData straightup
    callback play_media(int);
    callback toggle_play();
    callback media_file_select();
    callback media_folder_select();
    callback change_volume();
    callback seek_press();
    callback seek(int);
    callback load_home();

    in property <bool> media_playing: false;
    in property <bool> file_selected: false;
    in property <string> media_title: "No Song Selected";
    in property <string> media_artist: "-----------";
    out property <float> volume_level: 1.0;
    in-out property <int> current_time: 0;
    in property <int> total_duration: 0;
    in property <int> resume_update_flag: 0;
    in property <image> mainpage_background;

    in property <[MediaData]> media_list: [];

    VerticalLayout {
        menubar := CustomMenuBar {
            // width: root.width;
            // file_button => { root.media_file_select() }
        }

        if (menubar.current_page == 0) : MainPage {
            media_playing: root.media_playing;
            file_selected: root.file_selected;
            media_title: root.media_title;
            media_artist: root.media_artist;
            current_time <=> root.current_time;
            total_duration: root.total_duration;
            resume_update_flag: root.resume_update_flag;
            background_image: root.mainpage_background;
        }
        if (menubar.current_page == 1) : FilePage {
            font-family: root.default-font-family;
            media_list: root.media_list;
            media_from_file => { root.media_file_select() }
            media_from_folder => { root.media_folder_select() }
            play_media(i) => { root.play_media(i) }
        }
        
        playbar := PlayBar {
            // width: parent.width;
            // y: (parent.height - self.height);
            play_button => { root.toggle_play() }
            playing: root.media_playing;
            file_selected: root.file_selected;
            media_title: root.media_title;
            media_artist: media_artist;
            current_time <=> root.current_time;
            total_duration: root.total_duration;
            resume_update_flag: root.resume_update_flag;
            change_volume(level) => { root.volume_level = level; root.change_volume() }
            seek_press() => { root.seek_press() }
            seek(time) => { root.seek(time) }
        }
    }
}