import { HorizontalBox, VerticalBox, Button } from "std-widgets.slint";
import "fonts/Orbitron-VariableFont_wght.ttf";
import "fonts/Orbitron-Bold.ttf";
import "fonts/Orbitron-ExtraBold.ttf";

import { Palette } from "palette.slint";
import { PlayBar } from "playbar.slint";
import { MenuBar } from "menubar.slint";

export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 128px;
    min-height: 128px;
    max-width: 19200px;
    max-height: 10800px;
    // default-font-family: "Orbitron";
    background: #000000;

    callback check_if_pair_solved();
    callback play_button();
    callback file_button();
    callback change_volume();
    callback seek_press();
    callback seek(int);

    in property <bool> media_playing: false;
    in property <bool> file_selected: false;
    in property <string> media_title: "No Song Selected";
    in property <string> media_artist: "-----------";
    out property <float> volume_level: 1.0;
    in-out property <int> current_time: 0;
    in property <int> total_duration: 0;
    in property <int> resume_update_flag: 0;

    menubar := MenuBar {
        set_width: root.width;
        file_button => { root.file_button() }
    }

    playbar := PlayBar {
        width: parent.width;
        y: (parent.height - self.height);
        play_button => { root.play_button() }
        playing: root.media_playing;
        file_selected: root.file_selected;
        media_title: root.media_title;
        media_artist: media_artist;
        current_time <=> root.current_time;
        total_duration: root.total_duration;
        resume_update_flag: root.resume_update_flag;
        change_volume(level) => { root.volume_level = level; root.change_volume() }
        seek_press() => { root.seek_press() }
        seek(time) => { root.seek(time) }
    }

    main_area := Rectangle {
        width: root.width;
        height: (root.height - menubar.height - playbar.height);
        x: 0;
        y: menubar.height;
        Image { source: @image-url("images/Background Teku.png"); }
    }
}