import { HorizontalBox, VerticalBox, Palette, Button } from "std-widgets.slint";
import "fonts/Orbitron-VariableFont_wght.ttf";
import "fonts/Orbitron-Bold.ttf";
import "fonts/Orbitron-ExtraBold.ttf";

export component CustomMenuBar inherits Rectangle {
    // background: #ABCCD2;
    background: @linear-gradient(180deg, #C5EAEC 0%, #819C9C 50%, #484F51 100%);
    min-width: 800px;
    // preferred-width: 800px;
    height: 60px;
    x: 0px;
    y: 0px;

    in property <length> font-size: 12px;
    in property <length> label-padding: (self.font-size * 1.5);

    callback file_button();
    
    HorizontalLayout {
        padding-left: 15px;
        padding-right: 15px;
        spacing: -5px;

        home := Rectangle {
            background: #28373B;
            width: (root.height * 0.75);
            height: (root.height * 0.75);
            y: ((root.height - self.height) / 2);
            border-radius: 25px;

            HorizontalLayout {
                padding: 2px;
                Rectangle {
                    background: @linear-gradient(180deg, #A5CDD3 0%, #273537 50%, #202F30 100%);
                    // width: (parent.height * 0.75);
                    // height: (parent.height * 0.75);
                    y: ((root.height - self.height) / 2);
                    border-radius: 25px;
                    Image {
                        source: @image-url("icons/home.svg");
                        colorize: @linear-gradient(180deg, #D2F6F7 0%, #B6D8D9 50%, #484F51 100%);
                        width: (parent.height * 0.9);
                        height: (parent.height * 0.9);
                    }
                    TouchArea {
                        mouse-cursor: pointer;
                    }
                }
            }
        }

        connecting := Rectangle {
            background: #28373B;
            height: (root.height * 0.3);
            y: ((root.height - self.height) / 2);
            min-width: 15px;
            max-width: 150px;
            z: -1.0;
        }

        buttons := Rectangle {
            background: #28373B;
            width: clamp((root.width * 0.75), buttons_layout.min-width, 800px);
            height: (root.height * 0.75);
            y: ((root.height - self.height) / 2);
            border-top-left-radius: (self.height / 2);
            border-bottom-left-radius: (self.height / 2);
            border-top-right-radius: (self.height / 2);
            border-bottom-right-radius: (self.height / 2);

            buttons_layout := HorizontalLayout {
                padding: 2px;
                spacing: 2px;

                file := Rectangle {
                    background: @linear-gradient(180deg, #A5CDD3 0%, #273537 50%, #202F30 100%);
                    border-top-left-radius: (self.height / 2);
                    border-bottom-left-radius: (self.height / 2);
                    min-width: (file_label.width + root.label-padding);
                    file_label := Text {
                        color: white;
                        text: "FILE";
                        font-weight: 700;
                        font-family: "Orbitron";
                        font-size: root.font-size;
                    }
                    TouchArea {
                        mouse-cursor: pointer;
                        clicked => {
                            root.file_button();
                        }
                    }
                }

                preferences := Rectangle {
                    background: @linear-gradient(180deg, #A5CDD3 0%, #273537 50%, #202F30 100%);
                    height: (parent.height * 0.95);
                    min-width: (pref_label.width + root.label-padding);
                    pref_label := Text {
                        color: white;
                        text: "PREFERENCES";
                        font-weight: 800;
                        font-family: "Orbitron";
                        font-size: root.font-size;
                    }
                    TouchArea {
                        mouse-cursor: pointer;
                    }
                }

                capture-controls := Rectangle {
                    background: @linear-gradient(180deg, #A5CDD3 0%, #273537 50%, #202F30 100%);
                    height: (parent.height * 0.95);
                    min-width: (cap_label.width + root.label-padding);
                    cap_label := Text {
                        color: white;
                        text: "CAPTURE CONTROLS";
                        font-weight: 850;
                        font-family: "Orbitron";
                        font-size: root.font-size;
                    }
                    TouchArea {
                        mouse-cursor: pointer;
                    }
                }

                video := Rectangle {
                    background: @linear-gradient(180deg, #A5CDD3 0%, #273537 50%, #202F30 100%);
                    height: (parent.height * 0.95);
                    min-width: (vid_label.width + root.label-padding);
                    vid_label := Text {
                        color: white;
                        text: "VIDEO";
                        font-weight: 900;
                        font-family: "Orbitron";
                        font-size: root.font-size;
                    }
                    TouchArea {
                        mouse-cursor: pointer;
                    }
                }

                audio := Rectangle {
                    background: @linear-gradient(180deg, #A5CDD3 0%, #273537 50%, #202F30 100%);
                    height: (parent.height * 0.95);
                    border-top-right-radius: (self.height / 2);
                    border-bottom-right-radius: (self.height / 2);
                    min-width: (aud_label.width + root.label-padding);
                    aud_label := Text {
                        color: white;
                        text: "AUDIO";
                        font-weight: 700;
                        font-family: "Orbitron";
                        font-size: root.font-size;
                    }
                    TouchArea {
                        mouse-cursor: pointer;
                    }
                }
            }
        }
    }

}