export global Palette {
    in-out property <color> accent-background: #C5EAEC;
    in-out property <color> secondary-accent-background: #A5CDD3;
    in-out property <color> foreground: #819C9C;
    in-out property <brush> foreground-gradient: @linear-gradient(180deg, #799797 0%, #87b1b4 15%, #6f8888 80%, #484F51 100%);
    in-out property <brush> secondary-foreground-gradient: @linear-gradient(180deg, #445a5a 0%, #608083 15%, #415252 80%, #232d30 100%);
}