import { Slider, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { SlimSlider } from "edited-std-widgets/slider.slint";
import { Palette } from "palette.slint";
import "fonts/Orbitron-VariableFont_wght.ttf";
import "fonts/Orbitron-Bold.ttf";
import "fonts/Orbitron-ExtraBold.ttf";

component SeekBar {
    in-out property <int> current_time: 0;
    in property <int> total_duration;
    in property <bool> file_selected: false;
    // in property <length> width: 350px;
    in property <string> font-family: "Orbitron";
    in property <int> resume_update_flag;

    callback seek(int);
    callback press();

    function format_time(time: int) -> string {
        let time_as_secs = (time / 1000).floor();
        let mins = (time_as_secs / 60).floor();
        let secs = (time_as_secs - (mins * 60));
        if secs < 10 {
            return "\{mins}:0\{secs}";
        }
        return "\{mins}:\{secs}";
    }

    changed current_time => {
        slider.value = self.current_time;
    }

    HorizontalLayout {
        max-width: root.width;
        spacing: 5px;
        
        current_label := Text {
            font-family: root.font-family;
            text: root.file_selected ? "\{root.format_time(root.current_time)}" : "--:--";
            color: Palette.accent-background;
        }

        slider := SlimSlider {
            fill: Palette.secondary-accent-background;
            enabled: root.file_selected;
            // enabled: false;
            minimum: 0.0;
            maximum: root.total_duration;
            // width: clamp(root.width, 100px, 400px);
            value: root.current_time;
            changed => { root.press() }
            released(val) => { root.seek(val) }
        }

        total_label := Text {
            font-family: root.font-family;
            text: root.file_selected ? "\{root.format_time(root.total_duration)}" : "--:--";
            color: Palette.accent-background;
        }
    }
}

component NowPlaying inherits Rectangle {
    in property <string> title;
    in property <string> artist;
    in property <string> font-family;
    in property <color> font-colour;
    // width: layout
    width: layout.preferred-width;

    layout := VerticalLayout {
        padding: 15px;
    
        title := Text {
            // x: 15px;
            // y: 15px;
            text: root.title;
            font-family: root.font-family;
            letter-spacing: 1px;
            // color: root.background.brighter(2.5);
            color: root.font-colour;
        }

        artist := Text {
            text: root.artist;
            // x: 15px;
            // y: 30px;
            font-family: root.font-family;
            // color: root.background.brighter(2.5);
            color: root.font-colour;
        }

    }
}

export component PlayBar inherits Rectangle {
    // background: #ABCCD2;
    background: #28373B;
    preferred-width: 800px;
    height: 60px;
    min-width: now_playing.width + seekbar.min-width + volume.width;
    // x: 0px;
    in property <string> font-family: "Orbitron";

    callback play_button();
    callback change_volume(float);
    callback seek_press();
    callback seek(int);

    in property <bool> playing;
    in property <bool> file_selected: false;
    in property <string> media_title: "NO SONG SELECTED";
    in property <string> media_artist: "-----------";

    in-out property <int> current_time: 0;
    in property <int> total_duration;
    in property <int> resume_update_flag;

    now_playing := NowPlaying {
        y: 0;
        x: 0;
        title: root.media_title;
        artist: root.media_artist;
        font-family: root.font-family;
        font-colour: root.background.brighter(2.5);
    }

    volume := Rectangle {
        width: volume_layout.preferred-width;
        x: root.width - volume_layout.width;
        volume_layout := HorizontalLayout {
            padding: 15px;
            volume_bar := SlimSlider {
                fill : Palette.secondary-accent-background;
                value: 1.0;
                maximum: 1.0;
                minimum: 0.0;
                width: 100px;
                changed(value) => {
                    change_volume(value);
                }
            }
        }
    }

    play_button := Rectangle {
        background: #28373B;
        width: (parent.height * 0.6);
        height: self.width;
        y: ((parent.height / 2.75) - (self.height / 2));
        border-radius: 25px;
        animate width { duration: 50ms; }

        states [
            hover when ta.has-hover && !ta.pressed : {
                play_button.width: (parent.height * 0.65);
            }
        ]

        HorizontalLayout {
            padding: 2px;
            Rectangle {
                background: root.file_selected ? Palette.secondary-accent-background : #6f898d;
                // width: (parent.height * 0.75);
                // height: (parent.height * 0.75);
                y: ((parent.height - self.height) / 2);
                border-radius: 25px;
                Image {
                    source: root.playing ? @image-url("icons/pause.svg") : @image-url("icons/play.svg");
                    colorize: #28373B;
                    width: (parent.height * 0.9);
                    height: (parent.height * 0.9);
                }
                ta := TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        root.play_button();
                    }
                }
            }
        }
    }

    function find_width_constraint() {

    }
    seekbar := SeekBar {
        // width: clamp(root.width * 0.5, root.width - now_playing.width - volume.width, 350px);
        width: now_playing.width > volume.width ? ((root.width / 2) - now_playing.width) * 2 : ((root.width / 2) - volume.width) * 2;
        min-width: 250px;
        x: ((parent.width / 2) - (self.width / 2));
        y: ((parent.height * 0.75) - (self.height / 2));

        font-family: root.font-family;
        
        current_time <=> root.current_time;
        total_duration: root.total_duration;
        file_selected: root.file_selected;
        resume_update_flag: root.resume_update_flag;

        press() => { root.seek_press() }
        seek(val) => { root.seek(val); }
    }
}

